{
 "title": "Python litestar",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Python platform information",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(python_info{instance=\"$instance\"}, \"name\", \" \", \"implementation\", \"version\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$instance\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total user and system CPU time spent in seconds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(litestar_request_duration_seconds_count{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(litestar_request_duration_seconds_sum{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(litestar_request_duration_seconds_sum{instance=\"$instance\"}) / sum(litestar_request_duration_seconds_count{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_max_fds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests currently in progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "label_join(litestar_requests_in_progress{instance=\"$instance\"}, \"name\", \" \", \"method\", \"status_code\", \"path\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total duration of requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(litestar_request_duration_seconds_sum{instance=\"$instance\"}, \"name\", \" \", \"method\",\"status_code\",\"path\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(litestar_request_duration_seconds_count{instance=\"$instance\"}, \"name\", \" \", \"method\", \"status_code\", \"path\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time to a request",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(litestar_request_duration_seconds_sum{instance=\"$instance\"} / litestar_request_duration_seconds_count{instance=\"$instance\"}, \"name\", \" \", \"method\", \"status_code\", \"path\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Objects collected during gc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of times this generation was collected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "python_gc_collections_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uncollectable objects found during GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "python_gc_objects_uncollectable_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}